name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'Mangoshi'
        reponame: 'Audiohaven-Sandbox'
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        VUE_APP_BASE_URL: ${{ secrets.VUE_APP_BASE_URL }}
